# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: 📦 Instalar dependências
      run: npm ci

    - name: 🧪 Instalar Playwright
      run: npx playwright install --with-deps

    - name: 🧪 Rodar testes
      run: npx playwright test

  # Descomente se quiser incluir geração automática via IA local (precisa de infraestrutura)
  # - name: 🤖 Gerar testes via logs (Ollama precisa estar disponível)
  #   run: npx tsx tests/pom_component/generators/fromLogs.ts

    - name: ✅ Finalizado
      run: echo "Todos os testes executados com sucesso!"
